# Generated by Django 2.1.7 on 2019-04-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190401_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='individual',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dev',
            field=models.BooleanField(default=False, verbose_name='Разработчик'),
        ),
    ]
