# Generated by Django 2.1.7 on 2019-04-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190402_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='person',
            field=models.CharField(blank=True, choices=[('entity', 'Юридическое лицо'), ('individual', 'Физическое лицо')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('custome', 'Заявитель'), ('contractor', 'Подрядчик')], max_length=10),
        ),
    ]
