# Generated by Django 2.1.7 on 2019-04-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190402_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dev',
        ),
        migrations.AddField(
            model_name='customuser',
            name='entity_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
