# Generated by Django 2.1.7 on 2019-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190402_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entity_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя юр. лица'),
        ),
    ]
