# Generated by Django 2.1.7 on 2019-04-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190403_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('custome', 'Заявитель'), ('contractor', 'Подрядчик'), ('staff', 'Сотрудник')], max_length=10),
        ),
    ]
