# Generated by Django 2.1.7 on 2019-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190404_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person',
            field=models.CharField(blank=True, choices=[('entity', 'Юридическое лицо'), ('individual', 'Физическое лицо')], max_length=10, verbose_name='Лицо'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('custome', 'Заявитель'), ('contractor', 'Подрядчик'), ('staff', 'Сотрудник')], max_length=10, verbose_name='Роль'),
        ),
    ]
