# Generated by Django 2.1.7 on 2019-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190405_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permisson',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reviews',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
