# Generated by Django 2.1.7 on 2019-04-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190406_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='equip',
            field=models.FileField(blank=True, upload_to='', verbose_name='Техника'),
        ),
    ]
