# Generated by Django 2.1.7 on 2019-04-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='equip',
            field=models.FileField(blank=True, upload_to='uploads/user/%d/%m/%Y/equip/', verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='exp',
            field=models.FileField(blank=True, upload_to='uploads/user/%d/%m/%Y/exp/', verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='permission',
            field=models.FileField(blank=True, upload_to='uploads/user/%d/%m/%Y/permission/', verbose_name='Разрешения для работы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reviews',
            field=models.FileField(blank=True, upload_to='uploads/user/%d/%m/%Y/reviews/', verbose_name='Отзывы и рекомендации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff',
            field=models.FileField(blank=True, upload_to='uploads/user/%d/%m/%Y/staff/', verbose_name='Персонал'),
        ),
    ]
