# Generated by Django 2.2 on 2019-06-15 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('region', models.CharField(choices=[('1', 'Агрызский район'), ('2', 'Азнакаевский район'), ('3', 'Аксубаевский район'), ('4', 'Актанышский район'), ('5', 'Алексеевский район'), ('6', 'Алькеевский район'), ('7', 'Альметьевский район'), ('8', 'Апастовский район'), ('9', 'Арский район'), ('10', 'Атнинский район'), ('11', 'Бавлинский район'), ('12', 'Балтасинский район'), ('13', 'Бугульминский район'), ('14', 'Буинский район'), ('15', 'Верхнеуслонский район'), ('16', 'Высокогорский район'), ('17', 'Дрожжановский район'), ('18', 'Елабужский район'), ('19', 'Заинский район'), ('20', 'Зеленодольский '), ('21', 'Кайбицкий район'), ('22', 'Камско-Устьинский район'), ('23', 'Кукморский район'), ('24', 'Лаишевский район'), ('25', 'Лениногорский район'), ('26', 'Мамадышский район'), ('27', 'Менделеевский район'), ('28', 'Мензелинский район'), ('29', 'Муслюмовский район'), ('30', 'Нижнекамский район'), ('31', 'Новошешминский район'), ('32', 'Нурлатский район'), ('33', 'Пестречинский район'), ('34', 'Рыбно-Слободский район'), ('35', 'Сабинский район'), ('36', 'Сармановский район'), ('37', 'Спасский район'), ('38', 'Тетюшский район'), ('39', 'Тукаевский район'), ('40', 'Тюлячинский район'), ('41', 'Черемшанский район'), ('42', 'Чистопольский район'), ('43', 'Ютазинский район')], max_length=2, verbose_name='Район')),
                ('locality', models.CharField(max_length=100, verbose_name='Населённый пункт')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Тех. условия')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность')),
                ('image', models.ImageField(blank=True, upload_to=market.models.get_image_filename, verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Краткое описание работ')),
                ('extra_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('contract_id', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('oriented_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Приблизительная стоимость работ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('deadline', models.DateField(verbose_name='Конечный срок исполнения')),
                ('locality', models.CharField(max_length=100, verbose_name='Населённый пункт')),
                ('region', models.CharField(choices=[('1', 'Агрызский район'), ('2', 'Азнакаевский район'), ('3', 'Аксубаевский район'), ('4', 'Актанышский район'), ('5', 'Алексеевский район'), ('6', 'Алькеевский район'), ('7', 'Альметьевский район'), ('8', 'Апастовский район'), ('9', 'Арский район'), ('10', 'Атнинский район'), ('11', 'Бавлинский район'), ('12', 'Балтасинский район'), ('13', 'Бугульминский район'), ('14', 'Буинский район'), ('15', 'Верхнеуслонский район'), ('16', 'Высокогорский район'), ('17', 'Дрожжановский район'), ('18', 'Елабужский район'), ('19', 'Заинский район'), ('20', 'Зеленодольский '), ('21', 'Кайбицкий район'), ('22', 'Камско-Устьинский район'), ('23', 'Кукморский район'), ('24', 'Лаишевский район'), ('25', 'Лениногорский район'), ('26', 'Мамадышский район'), ('27', 'Менделеевский район'), ('28', 'Мензелинский район'), ('29', 'Муслюмовский район'), ('30', 'Нижнекамский район'), ('31', 'Новошешминский район'), ('32', 'Нурлатский район'), ('33', 'Пестречинский район'), ('34', 'Рыбно-Слободский район'), ('35', 'Сабинский район'), ('36', 'Сармановский район'), ('37', 'Спасский район'), ('38', 'Тетюшский район'), ('39', 'Тукаевский район'), ('40', 'Тюлячинский район'), ('41', 'Черемшанский район'), ('42', 'Чистопольский район'), ('43', 'Ютазинский район')], max_length=2, verbose_name='Район')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Тех. условия')),
                ('choosen_offer', models.IntegerField(blank=True, null=True, verbose_name='ID Выбранного предложения')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название материала')),
                ('price', models.PositiveIntegerField(verbose_name='Цена материала')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания предложения')),
                ('price', models.IntegerField(verbose_name='Предлагаемая цена')),
                ('desc', models.TextField(verbose_name='Описание работы подрядчика')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв по сделаной работе')),
                ('contractor_review', models.TextField(blank=True, verbose_name='Отчёт по сделаной работе')),
                ('raiting', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка сделанной работы')),
                ('work_done_custome', models.BooleanField(default=False, verbose_name='Заявитель завершение работы')),
                ('work_done_contractor', models.BooleanField(default=False, verbose_name='Подрядчик завершение работы')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Item', verbose_name='Работа')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подрядчик')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.models.get_image_filename, verbose_name='Фото')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Item')),
            ],
        ),
    ]
