# Generated by Django 2.1.7 on 2019-03-29 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_remove_item_start_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания предложения')),
                ('price', models.IntegerField(verbose_name='Предлагаемая цена')),
                ('desc', models.TextField(verbose_name='Описание работы подрядчика')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(verbose_name='Конечная дата выполнения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(verbose_name='Описание работ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название работ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_price',
            field=models.IntegerField(verbose_name='Начальная цена'),
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Item', verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подрядчик'),
        ),
    ]
