# Generated by Django 2.1.7 on 2019-04-03 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190403_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='oriented_price',
        ),
        migrations.AddField(
            model_name='item',
            name='contract_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 3, 16, 0, 58, 202034, tzinfo=utc), verbose_name='Дата договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='contract_id',
            field=models.CharField(default=1231234234, max_length=20, verbose_name='Номер договора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(verbose_name='Желаемый срок исполнения'),
        ),
    ]
