# Generated by Django 2.1.7 on 2019-04-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20190403_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
