# Generated by Django 2.1.7 on 2019-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержденно сотрудниками'),
        ),
    ]
