# Generated by Django 2.1.7 on 2019-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_item_oriented_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='locality',
            field=models.CharField(default='Казань', max_length=100, verbose_name='Населённый пункт'),
            preserve_default=False,
        ),
    ]
