# Generated by Django 2.1.7 on 2019-04-06 06:59

from django.db import migrations, models
import django.db.models.deletion
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_item_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=market.models.get_image_filename, verbose_name='Фото')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.CharField(choices=[('1', 'Агрызский район'), ('2', 'Азнакаевский район'), ('3', 'Аксубаевский район'), ('4', 'Актанышский район'), ('5', 'Алексеевский район'), ('6', 'Алькеевский район'), ('7', 'Альметьевский район'), ('8', 'Апастовский район'), ('9', 'Арский район'), ('10', 'Атнинский район'), ('11', 'Бавлинский район'), ('12', 'Балтасинский район'), ('13', 'Бугульминский район'), ('14', 'Буинский район'), ('15', 'Верхнеуслонский район'), ('16', 'Высокогорский район'), ('17', 'Дрожжановский район'), ('18', 'Елабужский район'), ('19', 'Заинский район'), ('20', 'Зеленодольский '), ('21', 'Кайбицкий район'), ('22', 'Камско-Устьинский район'), ('23', 'Кукморский район'), ('24', 'Лаишевский район'), ('25', 'Лениногорский район'), ('26', 'Мамадышский район'), ('27', 'Менделеевский район'), ('28', 'Мензелинский район'), ('29', 'Муслюмовский район'), ('30', 'Нижнекамский район'), ('31', 'Новошешминский район'), ('32', 'Нурлатский район'), ('33', 'Пестречинский район'), ('34', 'Рыбно-Слободский район'), ('35', 'Сабинский район'), ('36', 'Сармановский район'), ('37', 'Спасский район'), ('38', 'Тетюшский район'), ('39', 'Тукаевский район'), ('40', 'Тюлячинский район'), ('41', 'Черемшанский район'), ('42', 'Чистопольский район'), ('43', 'Ютазинский район')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл договора с Сетевой Компанией'),
        ),
        migrations.AddField(
            model_name='images',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.Item'),
        ),
    ]
