# Generated by Django 2.1.7 on 2019-04-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20190406_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='choosen',
            field=models.BooleanField(blank=True, default=False, verbose_name='Предложение выбранно'),
            preserve_default=False,
        ),
    ]
