# Generated by Django 2.1.7 on 2019-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_offer_choosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='choosen',
            field=models.BooleanField(default=False, verbose_name='Предложение выбранно'),
            preserve_default=False,
        ),
    ]
