# Generated by Django 2.1.7 on 2019-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20190406_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='choosen_offer',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Выбранного предложения'),
        ),
    ]
