# Generated by Django 2.1.7 on 2019-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_item_choosen_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Отзыв существует'),
        ),
    ]
