# Generated by Django 2.1.7 on 2019-04-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_offer_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingandreview',
            name='id',
        ),
        migrations.AlterField(
            model_name='ratingandreview',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='market.Offer'),
        ),
    ]
