# Generated by Django 2.1.7 on 2019-04-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_auto_20190406_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingandreview',
            name='id',
            field=models.AutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratingandreview',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Offer'),
        ),
    ]
