# Generated by Django 2.1.7 on 2019-04-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_auto_20190406_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingandreview',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='offer',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка сделанной работы'),
        ),
        migrations.AddField(
            model_name='offer',
            name='review',
            field=models.TextField(blank=True, verbose_name='Отзыв по сделаной работе'),
        ),
        migrations.DeleteModel(
            name='RatingAndReview',
        ),
    ]
