# Generated by Django 2.1.7 on 2019-04-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_auto_20190406_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='rating',
            new_name='raiting',
        ),
    ]
