# Generated by Django 2.1.7 on 2019-04-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_auto_20190406_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='raiting',
        ),
    ]
