# Generated by Django 2.1.7 on 2019-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_remove_offer_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='raiting',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка сделанной работы'),
        ),
    ]
