# Generated by Django 2.1.7 on 2019-04-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_auto_20190406_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='approved',
        ),
    ]
