# Generated by Django 2.1.7 on 2019-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_remove_item_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='work_done_contractor',
            field=models.BooleanField(default=False, verbose_name='Заявитель завершение работы'),
        ),
        migrations.AddField(
            model_name='offer',
            name='work_done_custome',
            field=models.BooleanField(default=False, verbose_name='Заявитель завершение работы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(verbose_name='Конечный срок исполнения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='oriented_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Конечная цена работ'),
        ),
    ]
