# Generated by Django 2.1.7 on 2019-04-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_auto_20190406_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contractor_review',
            field=models.TextField(blank=True, verbose_name='Отчёт по сделаной работе'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='work_done_contractor',
            field=models.BooleanField(default=False, verbose_name='Подрядчик завершение работы'),
        ),
    ]
