# Generated by Django 2.1.7 on 2019-04-07 07:04

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_contract_contract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='image',
            field=models.ImageField(blank=True, upload_to=market.models.get_image_filename, verbose_name='Фото'),
        ),
    ]
