# Generated by Django 2.1.7 on 2019-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_auto_20190407_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=300, verbose_name='Дата договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность'),
        ),
    ]
