# Generated by Django 2.1.7 on 2019-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_auto_20190407_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_date',
        ),
    ]
