# Generated by Django 2.1.7 on 2019-04-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0033_remove_contract_contract_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='power',
        ),
    ]
