# Generated by Django 2.1.7 on 2019-04-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_remove_contract_power'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
