# Generated by Django 2.1.7 on 2019-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0037_delete_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='desf',
            field=models.TextField(blank=True, verbose_name='Описание работы под123'),
        ),
    ]
