# Generated by Django 2.1.7 on 2019-04-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0038_offer_desf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='desf',
        ),
    ]
