# Generated by Django 2.1.7 on 2019-04-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
