# Generated by Django 2.1.7 on 2019-04-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность'),
        ),
    ]
