# Generated by Django 2.1.7 on 2019-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_offer_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='power',
        ),
        migrations.AddField(
            model_name='item',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность'),
        ),
    ]
